jenkins:
  image: training/jenkins
  container_name : training-jenkins
  ports:
  - "10000:8080"
  - "50000:50000"
  environment:
  - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
  volumes:
  - ./data/:/var/jenkins_home/
  - /etc/localtime:/etc/localtime:ro
  - ./jenkins/.vagrant/machines/default/virtualbox/private_key:/var/jenkins_home/.ssh/id_rsa